name: okn_dsp
description: OKN DSP V21 BETA2 Full Flutter Project
publish_to: none
version: 1.0.0+21

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.32.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
