name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4


      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'


      - name: Show files
        run: |
          ls -la
          find . -maxdepth 2 -type f


      - name: Extract ZIP
        run: |
          mkdir project
          unzip -o *.zip -d project


      - name: Find Project
        id: project
        run: |
          GRADLE=$(find project -name gradlew | head -1)

          if [ -z "$GRADLE" ]; then
            echo "NO GRADLE FOUND"
            exit 1
          fi

          DIR=$(dirname "$GRADLE")

          echo "DIR=$DIR"
          echo "dir=$DIR" >> $GITHUB_OUTPUT


      - name: Build APK
        run: |
          cd ${{ steps.project.outputs.dir }}
          chmod +x gradlew
          ./gradlew assembleDebug --stacktrace


      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: OKN_DSP_APK
          path: |
            project/**/build/outputs/apk/**/*.apk
