name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4


    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17


    - name: Find ZIP
      run: |
        ls -la
        find . -name "*.zip"


    - name: Extract ZIP
      run: |
        mkdir source
        unzip -o *.zip -d source
        echo "FILES:"
        find source -maxdepth 3 -type f | head -100


    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4


    - name: Find Gradle Project
      id: gradle
      run: |
        PROJECT=$(find source -name build.gradle -o -name build.gradle.kts | head -1 | xargs dirname)
        echo "PROJECT=$PROJECT"
        echo "PROJECT=$PROJECT" >> $GITHUB_ENV


    - name: Build APK
      run: |
        cd $PROJECT

        if [ -f gradlew ]; then
          chmod +x gradlew
          ./gradlew clean assembleDebug
        else
          gradle clean assembleDebug
        fi


    - name: Find APK
      run: |
        find . -name "*.apk"


    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: OKN_DSP_APK
        path: "**/*.apk"
