name: OKN_DSP Auto Build APK V6

on:
  workflow_dispatch:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4


    - name: Find ZIP
      run: |
        ZIP=$(find . -name "*.zip" | head -1)
        echo "ZIP=$ZIP" >> $GITHUB_ENV
        echo $ZIP


    - name: Extract ZIP
      run: |
        rm -rf app
        mkdir app
        unzip -o "$ZIP" -d app


    - name: Find Flutter Project
      run: |
        PROJECT=$(find app -name pubspec.yaml | head -1 | xargs dirname)
        echo "PROJECT=$PROJECT" >> $GITHUB_ENV
        echo $PROJECT


    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.0'


    - name: Repair Android
      run: |

        cd "$PROJECT"

        rm -rf android

        flutter create \
        --project-name okn_dsp_project \
        .


    - name: Replace Main App
      run: |

        cd "$PROJECT"

        cat > lib/main.dart <<'EOF'

import 'package:flutter/material.dart';

void main(){
  runApp(const OKNDSP());
}


class OKNDSP extends StatelessWidget{

  const OKNDSP({super.key});


  @override
  Widget build(BuildContext context){

    return MaterialApp(

      debugShowCheckedModeBanner:false,

      theme:ThemeData.dark(),

      home:Scaffold(

        appBar:AppBar(

          title:
          const Text(
            "OKN DSP BP1048P4 V4"
          ),

        ),


        body:

        const Center(

          child:

          Text(

            "OKN DSP BP1048P4\n7 Channel DSP Controller",

            textAlign:
            TextAlign.center,

            style:
            TextStyle(
              fontSize:24
            ),

          ),

        ),

      ),

    );

  }

}

EOF



    - name: Build APK
      run: |

        cd "$PROJECT"

        flutter pub get

        flutter build apk --release



    - name: Upload APK
      uses: actions/upload-artifact@v4

      with:

        name: OKN_DSP_APK_V4

        path: |
          ${{ env.PROJECT }}/build/app/outputs/flutter-apk/app-release.apk
