name: Build Android APK V40.9

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4


    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.5'
        channel: stable
        cache: true


    - name: Locate Flutter Project
      shell: bash
      run: |
        echo "Searching Flutter project..."

        PUBSPEC=$(find "$GITHUB_WORKSPACE" -name pubspec.yaml | head -n 1)

        if [ -z "$PUBSPEC" ]; then
          echo "ERROR: pubspec.yaml not found"
          exit 1
        fi

        PROJECT_DIR=$(dirname "$PUBSPEC")

        echo "Found:"
        echo "$PROJECT_DIR"

        echo "PROJECT_DIR=$PROJECT_DIR" >> $GITHUB_ENV


    - name: Flutter Doctor
      run: |
        flutter doctor -v


    - name: Flutter Pub Get
      shell: bash
      run: |
        cd "$PROJECT_DIR"
        echo "Current:"
        pwd
        flutter pub get


    - name: Flutter Clean
      shell: bash
      run: |
        cd "$PROJECT_DIR"
        flutter clean


    - name: Build APK
      shell: bash
      run: |
        cd "$PROJECT_DIR"
        flutter build apk --release


    - name: Find APK
      shell: bash
      run: |
        find "$PROJECT_DIR" -name "*.apk"


    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: OKN_DSP_BP1048P4_APK
        path: |
          **/app-release.apk
